name: C++ CI with GTest

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true   # важно для подтягивания third-party/gtest

    - name: Configure CMake
      run: cmake -H. -B_build -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build _build

    - name: Run tests (ctest)
      run: cmake --build _build --target test -- ARGS=--verbose

    - name: Also run check binary directly
      run: _build/check
