name: CMake and Docker CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    # Исправленный шаг клонирования с субмодулями
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Docker Image
      run: |
        docker build -t logger .

    - name: Verify Docker Image info
      run: |
        docker images logger
